apiVersion: v1
kind: Service
metadata:
  name: python-service-name                   # 🏷️ service name
spec:
  selector:
    app: python-app-label                     # 🔗 match pods by label
  ports:
    - protocol: TCP
      port: 80                                # external service port
      targetPort: 5000                        # internal container port
  type: NodePort
